[workspace]
members = [
    "crates/blendoc_testkit",
    "crates/blendoc_core",
    "crates/blendoc_cli",
    "tools/blendoc_blendfiles_downloader",
]
resolver = "2"

[workspace.lints.rust]
missing_docs = "warn"
